#!/bin/bash
# Local dev workflow for chat — runs lobehub Next.js dev server on
# http://localhost:3010 with hot reload, sharing the prod chat DB
# + OpenAI proxy. Iterate UI changes here, only build the docker
# image once we're satisfied.
#
# Pulls secrets from ssl-service admin's system_config so we don't
# duplicate them on disk.
#
# First run: ~5-10 min for pnpm install (1500 packages). Subsequent
# runs: ~10s startup.
set -e
cd "$(dirname "$0")/service-source/chat"

ADMIN="http://127.0.0.1:8088"
TOKEN="${SSL_SERVICE_ADMIN_TOKEN:-dev-token}"

echo "==> Sanity: node + pnpm available?"
node --version || { echo "node not installed — install Node 22 LTS"; exit 1; }
command -v pnpm >/dev/null || { echo "pnpm not installed — run 'npm i -g pnpm@10'"; exit 1; }
pnpm --version

echo "==> Fetching secrets from ssl-service admin API"
fetch_cfg () {
  curl -fsS -H "Authorization: Bearer $TOKEN" \
    "$ADMIN/api/system-config/$1" \
    | python3 -c "import sys,json; print(json.load(sys.stdin).get('$2',''))"
}

CHAT_DB_ID="$(cat .chat-db-id 2>/dev/null || echo '')"
if [[ -z "$CHAT_DB_ID" ]]; then
  CHAT_DB_ID="$(curl -fsS -H "Authorization: Bearer $TOKEN" "$ADMIN/api/databases" \
    | python3 -c 'import sys,json; print(next(e["id"] for e in json.load(sys.stdin).get("entries",[]) if e.get("label")=="chat"))')"
fi

# Pull DSN from registry — admin masks it via /api/databases, but
# the inline resolver path ?expand=dsn is not available. Cheat: use
# /api/databases/{id}/test which doesn't return dsn but confirms it.
# Instead build the DSN ourselves from .env (same pattern as
# chat-bootstrap.command).
ONE_DSN="$(awk -F= '/^SSL_SERVICE_PG_DSN=/{print substr($0, index($0,"=")+1)}' "$(dirname "$0")/.env")"
DEV_DSN="$(printf '%s\n' "$ONE_DSN" \
  | sed -E 's/[?&]options=[^&]*//' \
  | sed -E 's/sslmode=require/sslmode=no-verify/' \
  | sed -E 's|/postgres([?])|/chat\1|' \
  | sed -E 's/[?&]$//')"

OAI_KEY="$(fetch_cfg chat.openai api_key)"
OAI_URL="$(fetch_cfg chat.openai proxy_url)"
ENC_AUTH="$(fetch_cfg chat.encryption auth_secret)"
ENC_KV="$(fetch_cfg chat.encryption key_vaults_secret)"

echo "==> Writing .env.local"
cat > .env.local <<ENV
# Generated by chat-dev-local.command — do NOT commit.
# Shares the prod chat database; writes here ARE production writes.

PORT=3010
APP_URL=http://localhost:3010
SSRF_ALLOW_PRIVATE_IP_ADDRESS=1

DATABASE_DRIVER=node
DATABASE_URL=$DEV_DSN

OPENAI_API_KEY=$OAI_KEY
OPENAI_PROXY_URL=$OAI_URL
OPENAI_MODEL_LIST=+gpt-5.4,+gpt-5.5,+gpt-image-2,-all
DEFAULT_AGENT_CONFIG={"model":"gpt-5.4","provider":"openai"}

KEY_VAULTS_SECRET=$ENC_KV
AUTH_SECRET=$ENC_AUTH

AUTH_EMAIL_VERIFICATION=0
AUTH_DISABLE_EMAIL_PASSWORD=0
AUTH_ALLOWED_EMAILS=bitsfactor.com,bitsfactorcom@gmail.com
AUTH_SSO_PROVIDERS=

FEATURE_FLAGS=-market,-knowledge_base,-rag_eval,-edit_agent,-speech_to_text,-welcome_suggest,-changelog,-agent_self_iteration,-agent_onboarding,-agent_task,-cloud_promotion,+commercial_hide_github,+commercial_hide_docs

S3_ENDPOINT=https://s3.invalid.local/devchat-no-storage
S3_BUCKET=chat-no-storage
S3_ACCESS_KEY_ID=placeholder
S3_SECRET_ACCESS_KEY=placeholder

# All non-OpenAI providers gated off.
ENABLED_ANTHROPIC=0
ENABLED_GOOGLE=0
ENABLED_AZURE_OPENAI=0
ENABLED_DEEPSEEK=0
ENABLED_BFL=0
ENABLED_FAL=0
ENV
chmod 600 .env.local

if [[ ! -d node_modules ]]; then
  echo "==> First-time pnpm install (this takes ~5-10 min)"
  pnpm install --no-frozen-lockfile
else
  echo "==> node_modules already present — skipping install"
fi

echo
echo "==> Starting full dev stack (Next.js :3010 + Vite SPA :9876)"
echo "    Edits to source files hot-reload automatically."
echo "    Ctrl+C to stop."
echo
# pnpm dev runs scripts/devStartupSequence.mts → Next.js on :3010 + Vite
# SPA on :9876. dev:next alone is NOT enough: the SPA template fetcher
# in src/app/spa/[variants]/[[...path]]/route.ts fetches from the Vite
# origin, so every / request 500's with ECONNREFUSED if Vite isn't up.
exec pnpm dev
